version: '3.6'

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine    
    ports:
      - "5672:5672"
      - "15672:15672"
  app:
    build:
      context: .
      dockerfile: Rabbitproxy/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_HTTPS_PORT=8443
      - ASPNETCORE_URLS=https://+;http://+
      # Security, lol!
      - Kestrel__Certificates__Default__Path=./cert-rabbitproxy.pfx 
      - Kestrel__Certificates__Default__Password=test
    depends_on:
      - rabbitmq
    ports:
      - "8080:80"
      - "8443:443"
  worker:
    build:
      context: .
      dockerfile: Worker/Dockerfile
    environment:
      - RABBIT_HOST=rabbitmq
    depends_on:
      - rabbitmq